comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
